// This script intercepts all wheel events, stops propagation, and attempts to discern
// whether the event was generated by a touchpad input or mousewheel.  This is necessary
// for an animation to behave correctly on laptops using touchpad scroll @ small screen sizes.
// Note:  This will be fragile if user is switching between touchpad and mousewheel without refreshing
// the page.
// Seems like a very edge case.

// Decide whether source of scrolling is a mouse wheel or touchpad
// based on how many events are emitted within 100ms.  
let isTouchPad;
let eventCount = 0;
let eventCountStart;

const wheelhandle = function (evt) {
    let isTouchPadDefined = isTouchPad || typeof isTouchPad !== "undefined";
    console.log(isTouchPadDefined);
    if (!isTouchPadDefined) {
        if (eventCount === 0) {
            eventCountStart = new Date().getTime();
        }

        eventCount++;

        if (new Date().getTime() - eventCountStart > 100) {
                if (eventCount > 10) {
                    isTouchPad = true;
                } else {
                    isTouchPad = false;
                }
            isTouchPadDefined = true;
        }
    }

    if (isTouchPadDefined) {
        if(!isTouchPad) {
            document.dispatchEvent(new Event('WheelIsMouse'));
        }

        // Re-dispatch a wheel event so that window scrolling still occurs
        document.dispatchEvent(new WheelEvent({deltaY: 4}));
    }
}

// Add touchpad detection function (above) to document
document.addEventListener('wheel', wheelhandle);