import React from "react";
import ReactDOM from "react-dom";
import { BrowserRouter as Router } from "react-router-dom";

// Get shared styles.
import "commonStyles/_base.scss";
import "commonStyles/_colors.scss";
import "commonStyles/_hover-effect.scss";

// Get local components
import App from "./containers/App";
import ErrorBoundary from "legos/ErrorBoundary";

// Add script to distinguish wheel events generated by
// a touchpad from those generated by a mouse wheel
import "utils/syntheticWheelEvent";

const root = document.querySelector("#root");

ReactDOM.render(
    <Router>
        <ErrorBoundary>
            <App />
        </ErrorBoundary>
    </Router>,
    root
);
